# Generated by Django 4.0.4 on 2022-08-17 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=127)),
                ('model', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='measurements/')),
                ('is_approved', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measurements.device')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='getMeasurement', to='experiments.experiment')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_time', models.FloatField()),
                ('result', models.FloatField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getData', to='measurements.measurement')),
            ],
        ),
    ]
