# Generated by Django 4.2.1 on 2023-05-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511, verbose_name='Monomer')),
                ('Mw_cta', models.CharField(max_length=511)),
                ('density_g_per_ml_cta', models.CharField(max_length=511)),
                ('reflective_index_cta', models.CharField(max_length=511)),
                ('boiling_point_c_cta', models.CharField(max_length=511)),
                ('c_number_cta', models.CharField(max_length=511)),
            ],
            options={
                'verbose_name': 'cta',
                'verbose_name_plural': 'cta',
            },
        ),
        migrations.CreateModel(
            name='Monomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511, verbose_name='Monomer')),
                ('Mw', models.CharField(max_length=511)),
                ('density_g_per_ml', models.CharField(max_length=511)),
                ('boiling_point_celsius', models.CharField(max_length=511)),
                ('vapour_pressure_kPa', models.CharField(max_length=511)),
                ('viscosity_cP', models.CharField(max_length=511)),
                ('c_number', models.CharField(max_length=511)),
            ],
            options={
                'verbose_name': 'Monomer',
                'verbose_name_plural': 'Monomers',
            },
        ),
    ]
